version: "3"

services:
  db_ds:
    image: postgres:13.4-alpine
    container_name: db_ds
    restart: always
    volumes:
      - ../../var/pgdata_ds:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ds

  db_salesdb:
    image: postgres:13.4-alpine
    container_name: db_salesdb
    restart: always
    volumes:
      - ../../var/pgdata_salesdb:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: salesdb

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ../../var/redis_data:/var/lib/redis
      - ../../var/redis/rc.local:/etc/rc.local
    ports:
      - 127.0.0.1:6379:6379
