# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workspace_credit.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16workspace_credit.proto\x12\nmy_service\".\n\x16WorkspaceCreditRequest\x12\x14\n\x0cworkspace_id\x18\x01 \x01(\t\"3\n\x17WorkspaceCreditResponse\x12\x18\n\x10workspace_credit\x18\x01 \x01(\x02\x32p\n\x0fWorkspaceCredit\x12]\n\x12GetWorkspaceCredit\x12\".my_service.WorkspaceCreditRequest\x1a#.my_service.WorkspaceCreditResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workspace_credit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WORKSPACECREDITREQUEST']._serialized_start=38
  _globals['_WORKSPACECREDITREQUEST']._serialized_end=84
  _globals['_WORKSPACECREDITRESPONSE']._serialized_start=86
  _globals['_WORKSPACECREDITRESPONSE']._serialized_end=137
  _globals['_WORKSPACECREDIT']._serialized_start=139
  _globals['_WORKSPACECREDIT']._serialized_end=251
# @@protoc_insertion_point(module_scope)
